doctrine:
    dbal:
        dbname: '%env(string:DB_NAME)%'
        host: '%env(string:DB_HOST)%'
        port: '%env(string:DB_PORT)%'
        user: '%env(string:DB_USER)%'
        password: '%env(string:DB_PASSWORD)%'
        server_version: '%env(string:DB_VERSION)%'
        driver: '%env(string:DB_DRIVER)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            ownership: App\Doctrine\Filter\OwnershipFilter
            visibility: App\Doctrine\Filter\VisibilityFilter
        controller_resolver:
            auto_mapping: true
        dql:
            string_functions:
                cast: App\Doctrine\Query\AST\Functions\Cast

when@dev:
    doctrine:
        dbal:
            connections:
                default:
                    profiling_collect_backtrace: true

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test_%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
