framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true
    
    http_client:
        default_options:
            http_version: '2.0'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
