parameters:
    release: '1.6.5'
    default_locale: 'en'
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Api\:
        resource: '../api/*'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Api\Controller\:
        resource: '../api/Controller'
        tags: [ 'controller.service_arguments' ]

when@test:
    services:
        App\Tests\Factory\:
            resource: '../tests/Factory'