name: Build release image for Docker Hub
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_release_image:
    name: Build release image for Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: benjaminjonard/koillection
          ref: 1.6.2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: docker.io/koillection/koillection:latest,docker.io/koillection/koillection:1.6.2
          platforms: linux/amd64,linux/arm64
